tournee_infirmiers/availability/urls.py
from django.conf.urls import url

from . import views

app_name = 'availability'
urlpatterns = [
    url(r'^availability/list$', views.manage_availabilities, name='manage_availability'),
    url(r'^availability/new/(\d+)$', views.add_availability, name='add_availability'),
    url(r'^availability/choose_nurse$', views.choose_nurse, name='nurse_choice'),
    url(r'^ajax/remove_unique_availability$', views.remove_unique_availability, name='remove_unique_availability'),
    url(r'^ajax/remove_repeatly_availability_only_this_one$',
        views.remove_repeatly_availability_only_this_one, name='remove_repeatly_availability_only_this_one'),
    url(r'^ajax/remove_repeatly_availability_all$',
        views.remove_repeatly_availability_all, name='remove_repeatly_availability_all'),
]

tournee_infirmiers/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='root'),
    url(r'^home/', views.home, name='home'),
    url(r'^dashboard/(\d+)/(\d+)/(\d+)/(\d+)$', views.dashboard, name='dashboard_custom'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
]

tournee_infirmiers/patient/urls.py
from django.conf.urls import url

from . import views

app_name = 'patient'
urlpatterns = [
    url(r'patient/new/$', views.new_patient, name="new_patient"),
    url(r'patient/(\d+)$', views.patient_info, name="patient_info"),
    url(r'patient/list/$', views.patient_list, name="patient_list"),
    url(r'patient/(\d+)/delete/$', views.delete_patient, name="delete_patient"),
    url(r'patient/(\d+)/edit/$', views.edit_patient, name="edit_patient"),
]

tournee_infirmiers/tournee_infirmiers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('user.urls')),
	url(r'^', include('event.urls')),
	url(r'^', include('availability.urls')),
	url(r'^', include('treatment.urls')),
	url(r'^', include('optimizer.urls')),
	url(r'^', include('home.urls')),
	url(r'^', include('patient.urls')),
    url(r'^admin/', admin.site.urls),
]

tournee_infirmiers/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *
from user import views as user_views

app_name = 'user'
urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^register/new_nurse/$', nurse, name='new_nurse'),
    url(r'^register/save_office/$', create_office, name='create_office'),
    url(r'^register/success/$', register_success),
    url(r'^error_login/', user_views.error_login),
    url(r'^account/$', user_views.account, name='account'),
    url(r'^account/nurse/(\d+)$', user_views.nurse_info, name='nurse_info'),
    url(r'^nurse/(\d+)/edit$', user_views.edit_nurse_info, name='edit_nurse_info'),
    url(r'^office/edit/$', user_views.edit_office_info, name='edit_office_info'),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logged_out/$', auth_views.logout, {'template_name': 'user/logged_out.html'}, name='logout'),
]

tournee_infirmiers/availability/models.py
from django.db import models

from user.models import Nurse


# Create your models here.
class AvailabilityGroup(models.Model):
    FREQUENCY = (
        ('U', 'Unique',),
        ('D', 'Tous les jours',),
        ('W', 'Toutes les semaines',),
    )
    nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE)
    frequency = models.CharField(max_length=1, choices=FREQUENCY)

    def __str__(self):
        return "Group"


class Availability(models.Model):
    start_date = models.DateTimeField()
    duration = models.DurationField()
    availability_group = models.ForeignKey(AvailabilityGroup, on_delete=models.CASCADE)

    def __str__(self):
        return 'Disponiblité {0} le {1} {2} {3} à partir de {4}:{5}:{6} durant {7}'.format(
            self.availability_group.frequency,
            self.start_date.day, self.start_date.month, self.start_date.year,
            self.start_date.hour, self.start_date.minute, self.start_date.second,
            self.duration)

tournee_infirmiers/availability/forms.py
from django import forms
from django.forms.widgets import DateTimeInput


FREQUENCY_CHOICES = (('U', 'Unique',), ('D', 'Tous les jours',), ('W', 'Toutes les semaines',))
MONTHS = {1: ('Janvier'), 2: ('Février'), 3: ('Mars'), 4: ('Avril'),
          5: ('Mai'), 6: ('Juin'), 7: ('Juillet'), 8: ('Août'),
          9: ('Septembre'), 10: ('Octobre'), 11: ('Novembre'), 12: ('Décembre')}


# TODO : Red border for input when error
class AddAvailabilityForm(forms.Form):
    start_date = forms.DateTimeField(label='A partir de quand êtes-vous disponible ?',
                                     input_formats=['%d/%m/%Y %H:%M'], widget=DateTimeInput)
    duration = forms.DurationField(label='Combien de temps êtes-vous disponible ? (format HH:mm:ss)')
    frequency = forms.ChoiceField(label='Quelle est la fréquence de cette disponibilité ?',
                                  widget=forms.RadioSelect, choices=FREQUENCY_CHOICES)

    def __init__(self, *args, **kwargs):
        super(AddAvailabilityForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.attrs['class'] = 'form-control input-lg'
        self.fields['start_date'].widget.attrs['placeholder'] = 'Début de la disponibilité'
        self.fields['duration'].widget.attrs['class'] = 'form-control input-lg'
        self.fields['duration'].widget.attrs['placeholder'] = "Durée (HH:mm:ss)"

tournee_infirmiers/availability/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse

from availability.models import Availability, AvailabilityGroup
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from user.models import Nurse, Office

from availability.forms import AddAvailabilityForm

# Transactions
from django.db import IntegrityError, transaction

# Date 
from datetime import datetime, timedelta


# TODO restrict access to nurse

@login_required
@transaction.atomic
def add_availability(request, id_nurse):
    nurse = Nurse.objects.get(id=id_nurse)
    if request.method == "POST":
        add_availability_form = AddAvailabilityForm(request.POST)
        if add_availability_form.is_valid():
            start_date = add_availability_form.cleaned_data["start_date"]
            duration = add_availability_form.cleaned_data["duration"]
            frequency = add_availability_form.cleaned_data["frequency"]
            availability_group = AvailabilityGroup(nurse=nurse, frequency=frequency)
            availability_group.save()
            if frequency == "U":
                availability = Availability(start_date=start_date,
                                            duration=duration,
                                            availability_group=availability_group)
                availability.save()

            if frequency == "D":
                # TODO : Find a way to add every day long time
                # TODO : Tell user those availabilities are available for one month
                for k in range(1, 31):
                    start_date_one_day = start_date + timedelta(days=k)
                    availability = Availability(start_date=start_date_one_day,
                                                duration=duration,
                                                availability_group=availability_group)
                    availability.save()
            if frequency == "W":
                # TODO : Find a way to add every day long time
                # TODO : Tell user those availabilities are available for four month
                for k in range(1, 28):
                    start_date_one_week = start_date + timedelta(weeks=k)
                    availability = Availability(start_date=start_date_one_week,
                                                duration=duration,
                                                availability_group=availability_group)
                    availability.save()
            return redirect("availability:manage_availability")
    else:
        add_availability_form = AddAvailabilityForm()

    return render(request, 'availability/create_availability.html',
                  {"add_availability_form": add_availability_form,
                   'nurse_id': id_nurse,
                   'nurse': nurse})


@login_required
def manage_availabilities(request):
    try:
        office = request.user.office
        availabilities_sets = {}
        for nurse in office.nurse_set.all():
            availabilities_sets[nurse] = Availability.objects.filter(
                    availability_group__nurse=nurse).order_by('start_date')[:10]
        if len(availabilities_sets) == 0:
            return render(request, 'availability/manage_availabilities.html', {"office": True,
                                                                            "availabilities_sets": availabilities_sets,
                                                                            "exception_raised": True})
        else:
            return render(request, 'availability/manage_availabilities.html', {"office": True,
                                                                               "availabilities_sets": availabilities_sets})
    except Office.DoesNotExist:
        availabilities = Availability.objects.filter(availability_group__nurse=request.user.nurse).order_by(
            'start_date')[:10]
        return render(request, 'availability/manage_availabilities.html',
                      {"office": False, "availabilities": availabilities, "nurse": request.user.nurse})
    except Nurse.DoesNotExist:
        # TODO : display error message in a better way
        return render(request, 'availability/manage_availabilities.html',
                      {"exception_raised": True}
                      )


def remove_unique_availability(request):
    if request.is_ajax():
        if request.method == "POST":
            id_availability = request.POST["remove-unique-availability-id"]
            availability = Availability.objects.get(id=id_availability)
            availability_group = availability.availability_group

            availability_group.delete()
            print("ok")
            return HttpResponse("Availability removed")
        else:
            return HttpResponse("Not Post")
        # return render(request, 'service/add_services_register.html')
    else:
        return HttpResponse("Not ajax")


def remove_repeatly_availability_only_this_one(request):
    if request.is_ajax():
        if request.method == "POST":
            id_availability = request.POST["remove-repeated-availability-id"]
            availability = Availability.objects.get(id=id_availability)

            availability.delete()
            return HttpResponse("Availability removed")
        else:
            return HttpResponse("Not Post")
        # return render(request, 'service/add_services_register.html')
    else:
        return HttpResponse("Not ajax")


def remove_repeatly_availability_all(request):
    if request.is_ajax():
        if request.method == "POST":
            id_availability = request.POST["remove-repeated-availability-id"]
            availability = Availability.objects.get(id=id_availability)
            availability_group = availability.availability_group
            availability_group.delete()
            return HttpResponse("Availability removed")
        else:
            return HttpResponse("Not Post")
        # return render(request, 'service/add_services_register.html')
    else:
        return HttpResponse("Not ajax")


def choose_nurse(request):
    if request.user.office:
        nurses = request.user.office.nurse_set.all()
        return render(request, 'availability/nurse_choice.html', {'nurses': nurses})
    else:
        return redirect("availability:manage_availability", id_nurse=0)

tournee_infirmiers/availability/templates/availability/create_availability.html
{% extends "availability_layout.html" %}
{% load staticfiles %}
{% block availability_content %}

	<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="nav-availability">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:dashboard' %}">Mon tableau de bord</a></li>
                    <li class="active"><a href="{% url 'availability:manage_availability' %}">Mes horaires</a><span class="sr-only">(current)</span></li>
                    <li><a href="{% url 'patient:patient_list' %}">Mes patients</a></li>
                    <li><a href="{% url 'user:account' %}">Mon compte</a></li>
                </ul>
            </div>
        </div>
    </nav>

	<link rel="stylesheet" href="{% static 'availability/css/manage_availability_style.css' %}">
    {% if exception_raised %}
        <div class="container">
            <h3>Aucun(e) infirmier/infirmière enregistré</h3>
            <p>Avant de pouvoir ajouter des horaires, vous devez renseigner les infirmiers et infirmières pour qui vous voulez les renseigner !</p>
        </div>
    {% else %}
    <div class="container">

	    <div class="row basic_div">
    		<div class="col-sm-6 col-sm-offset-3">
    			<form method="post" action="{% url 'availability:add_availability' nurse_id %}">
				    {% csrf_token %}
				    <div class="basic_title_div row" >
	                	<h1 class="text-center">Ajouter une disponibilité à {{ nurse.first_name }} {{ nurse.last_name|upper }} </h1>
	           	 	</div>
				    <div class="form-group">
						{{ add_availability_form.start_date.label }}
						<div class="">
							{{ add_availability_form.start_date.errors }}
							<div class='input-group' id='datetimepicker1'>
							{{ add_availability_form.start_date }}
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-calendar"></span>
								</span>
						  	</div>
							
						</div>
					</div>
					 <div class="form-group">
						 {{ add_availability_form.duration.label }}
						<div class="">
							{{ add_availability_form.duration.errors }}
							{{ add_availability_form.duration }}
							
						</div>
					</div>
					 <div class="form-group">
						 {{ add_availability_form.frequency.label }}
						<div class="">
							{{ add_availability_form.frequency.errors }}
							{{ add_availability_form.frequency }}
							
						</div>
					</div>
				   	<div class="form-group">
						<div class="col-lg-10 col-lg-offset-1">
				    		<input id ="register_submit_button"
				    		class="center-block btn btn-lg btn-primary " 
				    		type="submit" value="Ajouter" />
				    	</div>
				    </div>
				</form>
    		</div>
    	</div>
    {% endif %}

  
    

{% endblock %}

{% block javascript_child %}
	<script type="text/javascript">
		function openfullCalModalRemoveRepeatlyAvailability(availabilityId){
	    	$('#remove-repeated-availability-id').val(availabilityId);
			$('#fullCalModalRemoveRepeatedAvailability').modal();
		}
		function openfullCalModalRemoveUniqueAvailability(availabilityId){
	    	$('#remove-unique-availability-id').val(availabilityId);
			$('#fullCalModalRemoveUniqueAvailability').modal();
		}
    </script>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#button_remove_unique_availability').click(function(event) {
				$('#fullCalModalRemoveUniqueAvailability').modal('hide');
				var $form = $('#form_remove_unique_availability');
				$.ajax({
					type: "POST",
					url:  "{% url 'availability:remove_unique_availability' %}",
					data: $form.serialize(),
					success: function(json) {
						location.reload();
					}
				});
			});
			$('#button_remove_repeated_availability_only_this_one').click(function(event) {
				$('#fullCalModalRemoveRepeatedAvailability').modal('hide');
				var $form = $('#form_remove_availability_repeated_availability');
				$.ajax({
					type: "POST",
					url:  "{% url 'availability:remove_repeatly_availability_only_this_one' %}",
					data: $form.serialize(),
					success: function(json) {
						location.reload();
					}
				});
			});
			$('#button_remove_repeated_availability_all').click(function(event) {
				$('#fullCalModalRemoveRepeatedAvailability').modal('hide');
				var $form = $('#form_remove_availability_repeated_availability');
				$.ajax({
					type: "POST",
					url:  "{% url 'availability:remove_repeatly_availability_all' %}",
					data: $form.serialize(),
					success: function(json) {
						location.reload();
					}
				});
			});
		});


	</script>

	<script type="text/javascript">
		$(function () {
			$('#datetimepicker1').datetimepicker({
				format: 'DD/MM/YYYY HH:mm'
			});
		});
	</script>

{% endblock %}

tournee_infirmiers/availability/templates/availability/manage_availabilities.html
{% extends "availability_layout.html" %}
{% load staticfiles %}
{% block availability_content %}

	<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="nav-availability">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:dashboard' %}">Mon tableau de bord</a></li>
                    <li class="active"><a href="{% url 'availability:manage_availability' %}">Mes horaires</a><span class="sr-only">(current)</span></li>
                    <li><a href="{% url 'patient:patient_list' %}">Mes patients</a></li>
                    <li><a href="{% url 'user:account' %}">Mon compte</a></li>
                </ul>
            </div>
        </div>
    </nav>

	<link rel="stylesheet" href="{% static 'availability/css/manage_availability_style.css' %}">
    {% if exception_raised %}
        <div class="container">
            <h3>Aucun(e) infirmier/infirmière enregistré</h3>
            <p>Avant de pouvoir ajouter des horaires, vous devez renseigner les infirmiers et infirmières pour qui vous voulez les renseigner !</p>
        </div>
    {% else %}
    <div class="container">

	    <div id="fullCalModalRemoveUniqueAvailability" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
						<h4 id="modalTitleRemoveUniqueAvailability" 
						class="modal-title center">Suppression de la plage de disponibilité</h4>
					</div>
					<div id="modalBodyRemoveUniqueAvailability" class="modal-body">
						<div id="modalBodyRemoveUniqueAvailability"> Voulez-vous supprimer cette plage de disponilité ? </div>
						<form id= "form_remove_unique_availability"  data-async method="POST">
							{% csrf_token %}
							<input  type="hidden" name="remove-unique-availability-id" id="remove-unique-availability-id" />
						</form>
						<div class="row" style="margin-top:10px;">
							<div class= "col-lg-6 center">
								<button id="button_remove_unique_availability" class="btn bbtn btn-danger">Confirmer la suppression</button>
							</div>
							<div class= "col-lg-6 center">
								<button id="button_not_remove_unique_availability" class="btn bbtn btn-success">Ne pas supprimer</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		 <div id="fullCalModalRemoveRepeatedAvailability" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
						<h4 id="modalTitleEdit" class="modal-title center">Suppression de la plage de disponibilité</h4>
					</div>
					<div id="modalBodyEdit" class="modal-body">
						<div id="modalBodyRemoveRepeatedAvailability"> Attention, cette plage de disponiblité est une plage répétée, voulez-vous supprimer seulement cette plage de disponilité ou aussi toutes celles associées ? </div>
						<form id= "form_remove_availability_repeated_availability"  data-async method="POST">
							{% csrf_token %}
							<input  type="hidden" name="remove-repeated-availability-id" id="remove-repeated-availability-id" />
						</form>
						<div class="row" style="margin-top:10px;">
							<div class= "col-lg-6 center">
								<button id="button_remove_repeated_availability_only_this_one" 
								class="btn btn-danger">Supprimer seulement cette disponiblité</button>
							</div>
							<div class= "col-lg-6 center">
								<button id="button_remove_repeated_availability_all" 
								class="btn btn-success">Supprimer les disponiblités associées</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

    	<div class="row">
	    	<div class = "col-lg-12">
	    		<div class="basic_title_div row" >
	            	<h1 class="text-center">Liste de vos disponibilités</h1>
	       	 	</div>
	       	 </div>
            {% if not office %}
                <p><a href="{% url "availability:add_availability" nurse.id %}"
                               class="btn btn-primary btn-lg .center-block" role="button">Ajouter</a> </p></p>
                 {% for availability in availabilities %}
                    <div class="row availability_div">
                        <div class="text-center col-lg-8">
                            {{ availability }}
                        </div>
                        <div class="col-lg-4">
                            {% if availability.availability_group.frequency == 'U' %}
                            <button class="center-block btn btn-danger"
                            onclick='openfullCalModalRemoveUniqueAvailability("{{availability.id}}")'>Supprimer </button>
                            {% else %}
                            <button class="center-block btn btn-danger"
                            onclick='openfullCalModalRemoveRepeatlyAvailability("{{availability.id}}")'>Supprimer </button>
                            {% endif %}
                        </div>
                    </div>
                    <hr>

                 {% endfor %}
            {% else  %}
                {% for nurse, availabilities in availabilities_sets.items %}
                    <div class="row availability_div">
                    <div class="nurse-div">
                        <p>{{ nurse.first_name }} {{ nurse.last_name|upper }}
                            <a href="{% url "availability:add_availability" nurse.id %}"
                               class="btn btn-primary btn-lg .center-block" role="button">Ajouter</a> </p>

                        {% for availability in availabilities %}
                        <div class="text-center col-lg-8">
                            {{ availability }}
                        </div>
                        <div class="col-lg-4">
                            {% if availability.availability_group.frequency == 'U' %}
                            <button class="center-block btn btn-danger"
                            onclick='openfullCalModalRemoveUniqueAvailability("{{availability.id}}")'>Supprimer </button>
                            {% else %}
                            <button class="center-block btn btn-danger"
                            onclick='openfullCalModalRemoveRepeatlyAvailability("{{availability.id}}")'>Supprimer </button>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    </div>
                    <hr>

                 {% endfor %}
            {% endif %}
    	</div>
    </div>
    {% endif %}

  
    

{% endblock %}

{% block javascript_child %}
	<script type="text/javascript">
		function openfullCalModalRemoveRepeatlyAvailability(availabilityId){
	    	$('#remove-repeated-availability-id').val(availabilityId);
			$('#fullCalModalRemoveRepeatedAvailability').modal();
		}
		function openfullCalModalRemoveUniqueAvailability(availabilityId){
	    	$('#remove-unique-availability-id').val(availabilityId);
			$('#fullCalModalRemoveUniqueAvailability').modal();
		}
    </script>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#button_remove_unique_availability').click(function(event) {
				$('#fullCalModalRemoveUniqueAvailability').modal('hide');
				var $form = $('#form_remove_unique_availability');
				$.ajax({
					type: "POST",
					url:  "{% url 'availability:remove_unique_availability' %}",
					data: $form.serialize(),
					success: function(json) {
						location.reload();
					}
				});
			});
            $('#button_not_remove_unique_availability').click(function(event) {
				$('#fullCalModalRemoveUniqueAvailability').modal('hide');
			});
			$('#button_remove_repeated_availability_only_this_one').click(function(event) {
				$('#fullCalModalRemoveRepeatedAvailability').modal('hide');
				var $form = $('#form_remove_availability_repeated_availability');
				$.ajax({
					type: "POST",
					url:  "{% url 'availability:remove_repeatly_availability_only_this_one' %}",
					data: $form.serialize(),
					success: function(json) {
						location.reload();
					}
				});
			});
			$('#button_remove_repeated_availability_all').click(function(event) {
				$('#fullCalModalRemoveRepeatedAvailability').modal('hide');
				var $form = $('#form_remove_availability_repeated_availability');
				$.ajax({
					type: "POST",
					url:  "{% url 'availability:remove_repeatly_availability_all' %}",
					data: $form.serialize(),
					success: function(json) {
						location.reload();
					}
				});
			});
		});
	</script>

{% endblock %}

tournee_infirmiers/availability/templates/availability/nurse_choice.html
{% extends "availability_layout.html" %}
{% load staticfiles %}
{% block availability_content %}

	<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="nav-availability">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:dashboard' %}">Mon tableau de bord</a></li>
                    <li class="active"><a href="{% url 'availability:manage_availability' %}">Mes horaires</a><span class="sr-only">(current)</span></li>
                    <li><a href="{% url 'patient:patient_list' %}">Mes patients</a></li>
                    <li><a href="{% url 'user:account' %}">Mon compte</a></li>
                </ul>
            </div>
        </div>
    </nav>

	<link rel="stylesheet" href="{% static 'availability/css/manage_availability_style.css' %}">
    <div class="container">

    	<div class="row basic_div">
	    	<div class = "col-lg-12">
	    		<div class="basic_title_div row" >
	            	<h1 class="text-center">Liste de vos infirmiers</h1>
	       	 	</div>
	       	 </div>
	       	 {% for nurse in nurses %}
	       	 	<div class="row availability_div">
	       	 		<div class="text-center col-lg-8">
	       	 			<a href="{% url "availability:manage_availability" nurse.id %}">{{ nurse.first_name }} {{ nurse.last_name|upper }}</a>
	       	 		</div>
	       	 	</div>
	       	 	<hr>
	       	 	
	       	 {% endfor %}
    	</div>
    </div>
    {% endif %}

  
    

{% endblock %}