tournee_infirmiers/availability/urls.py
from django.conf.urls import url

from . import views

app_name = 'availability'
urlpatterns = [
    url(r'^availability/list$', views.manage_availabilities, name='manage_availability'),
    url(r'^availability/new/(\d+)$', views.add_availability, name='add_availability'),
    url(r'^availability/choose_nurse$', views.choose_nurse, name='nurse_choice'),
    url(r'^ajax/remove_unique_availability$', views.remove_unique_availability, name='remove_unique_availability'),
    url(r'^ajax/remove_repeatly_availability_only_this_one$',
        views.remove_repeatly_availability_only_this_one, name='remove_repeatly_availability_only_this_one'),
    url(r'^ajax/remove_repeatly_availability_all$',
        views.remove_repeatly_availability_all, name='remove_repeatly_availability_all'),
]

tournee_infirmiers/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='root'),
    url(r'^home/', views.home, name='home'),
    url(r'^dashboard/(\d+)/(\d+)/(\d+)/(\d+)$', views.dashboard, name='dashboard_custom'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
]

tournee_infirmiers/patient/urls.py
from django.conf.urls import url

from . import views

app_name = 'patient'
urlpatterns = [
    url(r'patient/new/$', views.new_patient, name="new_patient"),
    url(r'patient/(\d+)$', views.patient_info, name="patient_info"),
    url(r'patient/list/$', views.patient_list, name="patient_list"),
    url(r'patient/(\d+)/delete/$', views.delete_patient, name="delete_patient"),
    url(r'patient/(\d+)/edit/$', views.edit_patient, name="edit_patient"),
]

tournee_infirmiers/tournee_infirmiers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('user.urls')),
	url(r'^', include('event.urls')),
	url(r'^', include('availability.urls')),
	url(r'^', include('treatment.urls')),
	url(r'^', include('optimizer.urls')),
	url(r'^', include('home.urls')),
	url(r'^', include('patient.urls')),
    url(r'^admin/', admin.site.urls),
]

tournee_infirmiers/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *
from user import views as user_views

app_name = 'user'
urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^register/new_nurse/$', nurse, name='new_nurse'),
    url(r'^register/save_office/$', create_office, name='create_office'),
    url(r'^register/success/$', register_success),
    url(r'^error_login/', user_views.error_login),
    url(r'^account/$', user_views.account, name='account'),
    url(r'^account/nurse/(\d+)$', user_views.nurse_info, name='nurse_info'),
    url(r'^nurse/(\d+)/edit$', user_views.edit_nurse_info, name='edit_nurse_info'),
    url(r'^office/edit/$', user_views.edit_office_info, name='edit_office_info'),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logged_out/$', auth_views.logout, {'template_name': 'user/logged_out.html'}, name='logout'),
]

tournee_infirmiers/user/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Person(models.Model):
    GENDER_CHOICES = (
        ('1', 'Homme',),
        ('2', 'Femme',),
    )
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    sex = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.CharField(max_length=255)
    postcode = models.IntegerField()
    city = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=255)
    birthdate = models.DateField(null=True, blank=True)

    class Meta:
        abstract = True


class Office(models.Model):
    address = models.CharField(max_length=255)
    postcode = models.IntegerField()
    city = models.CharField(max_length=255)
    geographical_area = models.IntegerField(default=30)  # Geographical area where nurse can go / in Km
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return "Office profile of {0}".format(self.user.username)


class Nurse(Person):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    office = models.ForeignKey(Office, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "Nurse profile of {0}".format(self.first_name)

tournee_infirmiers/user/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import RegexValidator


class RegistrationForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Nom d\'utilisateur'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label='Mot de passe',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Mot de passe'}))
    password2 = forms.CharField(label='Mot de passe (vérification)',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Mot de passe'}))
    USER_CHOICES = (
        ('1', 'Infirmier',),
        ('2', 'Cabinet',)
    )
    user_type = forms.ChoiceField(widget=forms.RadioSelect, choices=USER_CHOICES, label="Type d'utilisateur")

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Les mots de passe sont différents')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError(
                "Le nom d'utilisateur ne peut contenir que des caractères alphanumériques et underscore")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("Le nom d'utilisateur est déjà pris.")


class NurseForm(forms.Form):
    GENDER_CHOICES = (
        ('1', 'Homme',),
        ('2', 'Femme',)
    )

    sex = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDER_CHOICES, label="Genre")
    lastname = forms.CharField(max_length=255, label="Nom",
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom'}))
    firstname = forms.CharField(max_length=255, label="Prénom",
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prénom'}))
    birthdate = forms.DateField(label="Date de naissance", input_formats=['%d/%m/%Y'],
                                widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date de naissance'}))
    address = forms.CharField(max_length=255, label="Adresse",
                              widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adresse'}))
    postcode = forms.CharField(label="Code Postal",
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Code Postal'}),
                               validators=[RegexValidator(r'^[0-9]{5}$', 'Entrez un code postal valide')])
    city = forms.CharField(max_length=255, label="Ville",
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ville'}))
    email = forms.CharField(max_length=255, label="Email",
                            widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    phone = forms.CharField(max_length=255, label="Numéro de téléphone",
                            validators=[RegexValidator(r'^0[0-9]([ .-]?[0-9]{2}){4}$',
                                                       'Entrez un numéro de téléphone valide (et commençant par 0).')],
                            widget=forms.TextInput(
                                attrs={'class': 'form-control', 'placeholder': 'Numéro de téléphone'}))


class OfficeForm(forms.Form):
    address = forms.CharField(max_length=255, label="Adresse",
                              widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adresse'}))
    postcode = forms.CharField(label="Code Postal",
                               validators=[RegexValidator(r'^[0-9]{5}$', 'Entrez un code postal valide')],
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Code Postal'}))
    city = forms.CharField(max_length=255, label="Ville",
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ville'}))
    geographical_area = forms.IntegerField(label="Rayon géographique couvert",
                                           widget=forms.NumberInput(attrs={
                                               'class': 'form-control',
                                               'placeholder': 'Rayon géographique (en km)'
                                           }))

tournee_infirmiers/user/views.py
from .forms import *
from .models import *
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth import authenticate, login


def error_login(request):
    return render(request, 'user/error_login.html')


@login_required(redirect_field_name='account')
def account(request):
    return render(request, 'user/account.html', {'user': request.user})


@csrf_exempt
def register(request):
    invalid_form = False
    user_form = RegistrationForm(request.POST or None)
    if user_form.is_valid():
        user = User.objects.create_user(username=user_form.cleaned_data['username'],
                                            password=user_form.cleaned_data['password1'],
                                            email=user_form.cleaned_data['email'])
        user.save()

        user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password1'])
        login(request, user)
        if user_form.cleaned_data['user_type'] == '1':
            return redirect('user:new_nurse')
        else:
            return redirect('user:create_office')
    elif request.method == 'POST':
        invalid_form = True

    variables = RequestContext(request, {'form': user_form, 'invalid_form': invalid_form})
    return render_to_response('user/register.html', variables)


def nurse(request):
    form = NurseForm(request.POST or None, initial={'email': request.user.email})
    new_nurse = Nurse()
    if form.is_valid():
        new_nurse.sex = form.cleaned_data['sex']
        new_nurse.last_name = form.cleaned_data['lastname']
        new_nurse.first_name = form.cleaned_data['firstname']
        new_nurse.birthdate = form.cleaned_data['birthdate']
        new_nurse.address = form.cleaned_data['address']
        new_nurse.postcode = form.cleaned_data['postcode']
        new_nurse.city = form.cleaned_data['city']
        new_nurse.email = form.cleaned_data['email']
        new_nurse.phone = form.cleaned_data['phone']

        try:
            new_nurse.office = request.user.office
        except Office.DoesNotExist:
            new_nurse.user = request.user

        new_nurse.save()
        success = True

    return render(request, 'user/new_nurse.html', locals())


def register_success(request):
    return render_to_response(
        'user/success.html',
        context=RequestContext(request)
    )


def edit_nurse_info(request, id_nurse):
    nurse_to_edit = request.user.nurse if id_nurse == 0 else Nurse.objects.get(id=id_nurse)
    edit = True
    form = NurseForm(request.POST or None, initial={
            'sex': nurse_to_edit.sex,
            'lastname': nurse_to_edit.last_name,
            'firstname': nurse_to_edit.first_name,
            'birthdate': nurse_to_edit.birthdate,
            'address': nurse_to_edit.address,
            'postcode': nurse_to_edit.postcode,
            'city': nurse_to_edit.city,
            'email': nurse_to_edit.email,
            'phone': nurse_to_edit.phone,
        })

    if form.is_valid():
        nurse_to_edit.sex = form.cleaned_data['sex']
        nurse_to_edit.last_name = form.cleaned_data['lastname']
        nurse_to_edit.first_name = form.cleaned_data['firstname']
        nurse_to_edit.birthdate = form.cleaned_data['birthdate']
        nurse_to_edit.address = form.cleaned_data['address']
        nurse_to_edit.postcode = form.cleaned_data['postcode']
        nurse_to_edit.city = form.cleaned_data['city']
        nurse_to_edit.email = form.cleaned_data['email']
        nurse_to_edit.phone = form.cleaned_data['phone']

        nurse_to_edit.save()
        success = True

    return render(request, 'user/new_nurse.html', locals())


def create_office(request):
    form = OfficeForm(request.POST or None)
    office = Office()
    if form.is_valid():
        office.address = form.cleaned_data['address']
        office.postcode = form.cleaned_data['postcode']
        office.city = form.cleaned_data['city']
        office.geographical_area = form.cleaned_data['geographical_area']

        office.user = request.user

        office.save()
        success = True

    return render(request, 'user/new_office.html', locals())


def edit_office_info(request):
    office_to_edit = request.user.office
    edit = True
    form = OfficeForm(request.POST or None, initial={
        'address' : office_to_edit.address,
        'postcode': office_to_edit.postcode,
        'city': office_to_edit.city,
        'geographical_area': office_to_edit.geographical_area
    })

    if form.is_valid():
        office_to_edit.address = form.cleaned_data['address']
        office_to_edit.postcode = form.cleaned_data['postcode']
        office_to_edit.city = form.cleaned_data['city']
        office_to_edit.geographical_area = form.cleaned_data['geographical_area']

        office_to_edit.user = request.user

        office_to_edit.save()
        success = True

    return render(request, 'user/new_office.html', locals())


def nurse_info(request, id_nurse):
    try:
        nurse_to_show = Nurse.objects.get(id=id_nurse)
        return render(request, 'user/account.html', {'nurse': nurse_to_show})
    except Nurse.DoesNotExist:
        # TODO properly handle exception
        pass

tournee_infirmiers/user/templates/user/account.html
{% extends "base.html" %}

{% block body %}

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="nav-account">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home:dashboard' %}">Mon tableau de bord</a></li>
                    <li><a href="{% url 'availability:manage_availability' %}">Mes horaires</a></li>
                    <li><a href="{% url 'patient:patient_list' %}">Mes patients</a></li>
                    <li class="active"><a href="{% url 'user:account' %}">Mon compte</a><span class="sr-only">(current)</span></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                {% if not nurse %}
               	<h2>Mon compte</h2>
                {% endif %}
            </div>
            <div class="col-sm-12">
                <div class="col-sm-6 col-sm-offset-3">
                    {% if user.nurse %}
                    <table class="table table-striped">
                        <tr>
                            <td>Nom</td>
                            <td>{{ user.nurse.last_name|upper }}</td>
                        </tr>
                        <tr>
                            <td>Prénom</td>
                            <td>{{ user.nurse.first_name }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>{{ user.nurse.email }}</td>
                        </tr>
                        <tr>
                            <td>Adresse</td>
                            <td>{{ user.nurse.address }}</td>
                        </tr>
                        <tr>
                            <td>Code postal</td>
                            <td>{{ user.nurse.postcode }}</td>
                        </tr>
                        <tr>
                            <td>Ville</td>
                            <td>{{ user.nurse.city|upper }}</td>
                        </tr>
                        <tr>
                            <td>Date de naissance</td>
                            <td>{{ user.nurse.birthdate|date }}</td>
                        </tr>
                    </table>
                    <a href="{% url 'user:edit_nurse_info' 0 %}" class="btn btn-warning btn-lg" role="button">Modifier les informations</a>

                    {% elif nurse %}

                    <table class="table table-striped">
                        <tr>
                            <td>Nom</td>
                            <td>{{ nurse.last_name|upper }}</td>
                        </tr>
                        <tr>
                            <td>Prénom</td>
                            <td>{{ nurse.first_name }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>{{ nurse.email }}</td>
                        </tr>
                        <tr>
                            <td>Adresse</td>
                            <td>{{ nurse.address }}</td>
                        </tr>
                        <tr>
                            <td>Code postal</td>
                            <td>{{ nurse.postcode }}</td>
                        </tr>
                        <tr>
                            <td>Ville</td>
                            <td>{{ nurse.city|upper }}</td>
                        </tr>
                        <tr>
                            <td>Date de naissance</td>
                            <td>{{ nurse.birthdate|date }}</td>
                        </tr>
                    </table>
                    <a href="{% url 'user:edit_nurse_info' nurse.id %}" class="btn btn-warning btn-lg" role="button">Modifier les informations</a>
                    <a href="{% url 'user:account' %}" class="btn btn-info btn-lg" role="button">Retour à mon compte</a>


                    {% elif user.office %}
                        <table class="table table-striped">
                        <tr>
                            <td>Nom d'utilisateur</td>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <td>Adresse</td>
                            <td>{{ user.office.address }}</td>
                        </tr>
                        <tr>
                            <td>Code postal</td>
                            <td>{{ user.office.postcode }}</td>
                        </tr>
                        <tr>
                            <td>Ville</td>
                            <td>{{ user.office.city|upper }}</td>
                        </tr>
                        <tr>
                            <td>Distance couverte (km)</td>
                            <td>{{ user.office.geographical_area }}</td>
                        </tr>
                    </table>

                        <h3>Les infirmiers de mon cabinet</h3>
                        <ul class="list-group">
                        {% for nurse in user.office.nurse_set.all %}
                            <a href="{% url 'user:nurse_info' nurse.id %}" class="list-group-item">{{ nurse.first_name }} {{ nurse.last_name|upper }}</a>
                        {%  endfor %}
                        </ul>

                        <a href="{% url 'user:edit_office_info' %}" class="btn btn-warning btn-lg" role="button">Modifier les informations</a>
                        <a href="{% url 'user:new_nurse' %}" class="btn btn-default btn-lg" role="button">Ajouter un infirmier</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

tournee_infirmiers/user/templates/user/error_login.html
{% extends "user_layout.html" %}

{% block user_content %}

<div class="container">
    <div class="page-header">
    <h1>Vous avez besoin d'être authentifié pour accéder à cette page.</h1>
    <</div>

    <p class="lead"><a href="{% url 'user:login' %}">Se connecter</a></p>

</div>
{% endblock %}

tournee_infirmiers/user/templates/user/logged_out.html
{% extends "user_layout.html" %}

{% block user_content %}

<div class="container">

    <div class="page-header">
    <h1>Vous avez bien été déconnecté !</h1>
    </div>

    <p class="lead"><a href="{% url 'user:login' %}">Se reconnecter</a> de nouveau.</p>
    <p>Accéder à <a href="{% url 'home:home' %}">l'accueil</a>.</p>
</div>


{% endblock %}

tournee_infirmiers/user/templates/user/login.html
{% extends 'user_layout.html' %}

{% block user_content %}

<div class="container">
    <div class="page-header">
    <h2>Se connecter</h2>
    </div>

    {% if form.errors %}
    <p>Erreur dans la saisie du nom d'utilisateur et du mot de passe.</p>
    {% endif %}

    {% if request.user.is_authenticated %}
    <p>Vous êtes déjà connecté sur la plateforme. Pour accéder à votre tableau de bord, cliquez <a
            href="{% url 'home:dashboard' %}">ici</a>.</p>
    {% else %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Nom d'utilisateur</label>
            <input type="text" class="form-control" placeholder="Nom d'utilisateur" autofocus="" id="id_username"
                   maxlength="254" name="username" required>
        </div>
        <div class="form-group">
            <label>Mot de passe</label>
            <input type="password" class="form-control" placeholder="Mot de passe" id="id_password" name="password"
                   required>
        </div>
        <input class="btn btn-default" type="submit" value="Connexion"/>
        <input type="hidden" name="next" value="{{ next }}"/>
    </form>
    {% endif %}

</div>

{% endblock %}

tournee_infirmiers/user/templates/user/new_nurse.html
{% extends "user_layout.html" %}
{% load staticfiles %}
{% block user_content %}

    <div class="container">
    <div class="page-header">
    {% if edit %}
        <h1> Modifier les informations </h1>
    {% else %}
        <h1> Veuillez compléter vos informations </h1>
    {% endif %}
    </div>


    {%if success %}
        <div>Vos informations ont bien été enregistrées !</div>

        <div id="successModal" class="modal fade">
            <div class="modal-dialog" style="margin-top: 20%;">
                <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal" style="margin:10px;"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                    <div class="modal-body">
                        <p class="text-center">Vos informations ont bien été enregistrées !</p>
                        <div class="text-center">
                            <a id="button_back" class="btn btn-success" href="{% url 'home:dashboard' %}" role="button">Retour à l'accueil</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {%endif%}

    <div>
    <a href="{% url 'user:account' %}" class="btn btn-primary btn-lg .center-block" role="button">Retour</a>
    </div>

    {% if edit %}
        <form action="{% url 'user:edit_nurse_info' id_nurse %}" method="post">
    {% else %}
        <form action="{% url 'user:new_nurse' %}" method="post">
    {% endif %}
        {%csrf_token%}
            {% for error in form.non_field_errors %}
            <div class="form-group has-errors text-danger small">
                {{error}}
            </div>
            {% endfor %}
            {% for field in form %}
            <div class="form-group has-errors text-danger small">
                {{field.errors}}
            </div>
            <div class="form-group has-errors text-danger small">
            </div>
            {% if field.label == 'Date de naissance' %}
                <div class="form-group">
                    {{ field.label }}
                  <div class='input-group' id='datetimepicker12'>
                    {{ field }}
                    <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                  </div>
                </div>
            {% else %}
                <div class="form-group">
                    {{field.label}}
                    {{field}}
                </div>
            {% endif %}
            {% endfor %}
            <input class="btn btn-default" type="submit" value="Valider"/>
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>

    </div>

{% endblock %}

{% block javascript_child %}

<script type="text/javascript">
    $(function () {
        $('#datetimepicker12').datetimepicker({
            viewMode: 'years',
            format: 'DD/MM/YYYY'
        });
    });
    {%if success %}
    $(document).ready(function() {
        $('#successModal').modal();
            });
    {% endif %}
</script>

{% endblock %}

tournee_infirmiers/user/templates/user/new_office.html
{% extends "user_layout.html" %}
{% load staticfiles %}
{% block user_content %}

    <div class="container">

    <div class="page-header">
    {% if edit %}
        <h1> Modifier mes informations </h1>
    {% else %}
        <h1> Veuillez compléter vos informations </h1>
    {% endif %}
    </div>


    {%if success %}
        <div>Vos informations ont bien été enregistrées !</div>

        <div id="successModal" class="modal fade">
            <div class="modal-dialog" style="margin-top: 20%;">
                <div class="modal-content">
                    <button type="button" class="close" data-dismiss="modal" style="margin:10px;"><span aria-hidden="true">×</span> <span class="sr-only">close</span></button>
                    <div class="modal-body">
                        <p class="text-center">Vos informations ont bien été enregistrées !</p>
                        <div class="text-center">
                            <a id="button_back" class="btn btn-success" href="{% url 'home:dashboard' %}" role="button">Retour à l'accueil</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {%endif%}

    <div>
    <a href="{% url 'user:account' %}" class="btn btn-primary btn-lg .center-block" role="button">Retour</a>
    </div>

    {% if edit %}
        <form action="{% url 'user:edit_office_info' %}" method="post">
    {% else %}
        <form action="{% url 'user:create_office' %}" method="post">
    {% endif %}
        {%csrf_token%}
            {% for error in form.non_field_errors %}
            <div class="form-group has-errors text-danger small">
                {{error}}
            </div>
            {% endfor %}
            {% for field in form %}
            <div class="form-group has-errors text-danger small">
                {{field.errors}}
            </div>
            <div class="form-group has-errors text-danger small">
            </div>
            <div class="form-group">
                {{field.label}}
                {{field}}
            </div>
            {% endfor %}
            <input class="btn btn-default" type="submit" value="Valider"/>
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>

    </div>

{% endblock %}

{% block javascript_child %}
<script type="text/javascript">
    {%if success %}
    $(document).ready(function() {
        $('#successModal').modal();
            });
    {% endif %}
</script>
{% endblock %}

tournee_infirmiers/user/templates/user/register.html
{% extends 'user_layout.html' %}

{% block user_content %}

<div class="container">

<div class="page-header">
    <h1>Inscrivez-vous sur la plateforme</h1>
</div>

    <form action="{%  url 'user:register' %}" method="post">

        {%csrf_token%}
            {% for error in form.non_field_errors %}
            <div class="form-group has-errors text-danger small">
                {{error}}
            </div>
            {% endfor %}
            {% for field in form %}
            <div class="form-group has-errors text-danger small">
                {{field.errors}}
            </div>
            <div class="form-group has-errors text-danger small">
            </div>
            <div class="form-group">
                {{field.label}}
                {{field}}
            </div>
            {% endfor %}
            <input class="btn btn-default" type="submit" value="S'inscrire"/>
            <input type="hidden" name="next" value="{{ next }}"/>

    </form>
</div>

{% endblock %}

tournee_infirmiers/user/templates/user/success.html
{% extends 'user_layout.html' %}

{% block user_content %}

<div class="container">
    <h1>Vous êtes bien enregistré</h1>
</div>
{% endblock %}