tournee_infirmiers/event/urls.py
from django.conf.urls import url
from . import views


app_name = 'event'
urlpatterns = [
    url(r'^patient/(\d+)/add_need/', views.add_need, name='add_need'),
    url(r'^appointment/(\d+)$', views.appointment_detail, name='appointment_detail')
]

tournee_infirmiers/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='root'),
    url(r'^home/', views.home, name='home'),
    url(r'^dashboard/(\d+)/(\d+)/(\d+)/(\d+)$', views.dashboard, name='dashboard_custom'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
]

tournee_infirmiers/optimizer/urls.py
from django.conf.urls import url
from optimizer import views as optimizer_views

from . import views

app_name = 'optimizer'
urlpatterns = [
    url(r'^optimize/$', optimizer_views.optimize, name="optimize"),
    url(r'^generate-matrix/$', optimizer_views.create_distance_matrix, name="create_matrix"),
]

tournee_infirmiers/patient/urls.py
from django.conf.urls import url

from . import views

app_name = 'patient'
urlpatterns = [
    url(r'patient/new/$', views.new_patient, name="new_patient"),
    url(r'patient/(\d+)$', views.patient_info, name="patient_info"),
    url(r'patient/list/$', views.patient_list, name="patient_list"),
    url(r'patient/(\d+)/delete/$', views.delete_patient, name="delete_patient"),
    url(r'patient/(\d+)/edit/$', views.edit_patient, name="edit_patient"),
]

tournee_infirmiers/tournee_infirmiers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('user.urls')),
	url(r'^', include('event.urls')),
	url(r'^', include('availability.urls')),
	url(r'^', include('treatment.urls')),
	url(r'^', include('optimizer.urls')),
	url(r'^', include('home.urls')),
	url(r'^', include('patient.urls')),
    url(r'^admin/', admin.site.urls),
]

tournee_infirmiers/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *
from user import views as user_views

app_name = 'user'
urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^register/new_nurse/$', nurse, name='new_nurse'),
    url(r'^register/save_office/$', create_office, name='create_office'),
    url(r'^register/success/$', register_success),
    url(r'^error_login/', user_views.error_login),
    url(r'^account/$', user_views.account, name='account'),
    url(r'^account/nurse/(\d+)$', user_views.nurse_info, name='nurse_info'),
    url(r'^nurse/(\d+)/edit$', user_views.edit_nurse_info, name='edit_nurse_info'),
    url(r'^office/edit/$', user_views.edit_office_info, name='edit_office_info'),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logged_out/$', auth_views.logout, {'template_name': 'user/logged_out.html'}, name='logout'),
]

tournee_infirmiers/home/models.py
from django.db import models

# Create your models here.

tournee_infirmiers/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import optimizer.views as opt
from datetime import datetime, timedelta
from user.models import Office, Nurse
from event.models import Need
from optimizer.forms import OptimizerDateForm


# Create your views here.
def home(request):
    if request.user.is_authenticated():
        return redirect('dashboard/')
    else:
        return render(request, 'home/home.html')


@login_required(redirect_field_name='dashboard')
def dashboard(request, year=None, month=None, day=None, user_id=None):
    now = datetime.now()
    year = year if year is not None else now.year
    month = month if month is not None else now.month
    day = day if day is not None else now.day

    form = OptimizerDateForm(None)

    appointments = get_next_appointments(request)

    # Filter most urgent needs : displays all needs needed between today and a week from today.
    most_urgent_needs = Need.objects.filter(
        date__gte=datetime.today()).exclude(date__gte=datetime.today() + timedelta(days=7))

    # print(year, month, day, nurse_id, schedule)
    return render(request, 'home/dashboard.html', {"appointments": appointments,
                                                   "needs": most_urgent_needs,
                                                   "form": form})


# Get the next appointments to display on the dashboards
# handles the different user cases (office or nurse)
def get_next_appointments(request):
    appointments = []
    try:
        office = request.user.office
        for nurse in office.nurse_set.all():
            for appointment in nurse.appointment_set.filter(
                    start__gte=datetime.today()).exclude(start__gte=datetime.today() + timedelta(days=7)):
                patient = appointment.need.patient
                appointments.append((appointment, patient))

    except Office.DoesNotExist:
        try:
            nurse = request.user.nurse
            for appointment in nurse.appointment_set.filter(
                    start__gte=datetime.today()).exclude(start__gte=datetime.today() + timedelta(days=7)):
                patient = appointment.need.patient
                appointments.append((appointment, patient))
        except Nurse.DoesNotExist:
            pass

    appointments = sorted(appointments, key=get_start_time)
    return appointments


def get_start_time(tuple_app_p):
    return tuple_app_p[0].start

tournee_infirmiers/home/templates/home/dashboard.html
{% extends "home_layout.html" %}
{% load staticfiles %}
{% block home_content %}

    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="../../static/home/js/googleMaps.js"></script>

    <section>

        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="nav-home">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'home:dashboard' %}">Mon tableau de bord<span
                                class="sr-only">(current)</span></a>
                        </li>
                        <li><a href="{% url 'availability:manage_availability' %}">Mes horaires</a></li>
                        <li><a href="{% url 'patient:patient_list' %}">Mes patients</a></li>
                        <li><a href="{% url 'user:account' %}">Mon compte</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">

            <div class="container">
                <div class="row">
                <form action="{% url 'optimizer:optimize' %}" method="post" id="optimizeForm">
                    <div class="col-sm-5">
                            {%csrf_token%}
                            {% for error in form.non_field_errors %}
                            <div class="form-group has-errors text-danger small">
                                {{error}}
                            </div>
                            {% endfor %}
                            {% for field in form %}
                            <div class="form-group has-errors text-danger small">
                                {{field.errors}}
                            </div>
                            <div class="form-group has-errors text-danger small">
                            </div>
                                {% if field.label == "Date de la tournée à optimiser (si laissé vide, Aujourd'hui par défaut)" %}
                                    <div class="form-group">
                                        {{ field.label }}
                                      <div class='input-group' id='datetimepicker12'>
                                        {{ field }}
                                        <span class="input-group-addon">
                                          <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                      </div>
                                    </div>
                                {% else %}
                                    <div class="form-group">
                                        {{field.label}}
                                        {{field}}
                                    </div>
                                {% endif %}
                            {% endfor %}

                    </div>
                    <div class="col-xs-6 col-xs-offset-1 dashboard_div">
                        <button type="button" role="button"
                                class="btn btn-primary btn-block"
                                data-loading-text="Optimisation en cours..." id="button-optimize">
                            <h4>Optimiser ma tournée</h4>
                        </button>
                        <h4>
                            <div id="success-optimize"></div>
                        </h4>
                    </div>
                </form>
                </div>
            </div>

            <br/>

            <div class="row">

                <!-- Main block displaying appointments -->
                <div class="col-md-6">

                    <p class="text-center">Mes prochains rendez-vous</p>

                    <div class="table-responsive">
                        <table class="table table-stripped">
                            <tr>
                                <th style="width:75px;">Date</th>
                                <th>Infirmier en charge</th>
                                <th>Patient</th>
                                <th colspan="2">Adresse</th>
                            </tr>
                            {% for appointment, patient in appointments %}
                                <tr class="clickable-row"
                                    data-href="{% url 'event:appointment_detail' appointment.id %}">
                                    <td class="dates">{{ appointment.start|date:"d-m-y" }}</td>
                                    <td class="nurses">{{ appointment.nurse.first_name }} {{ appointment.nurse.last_name }}</td>
                                    <td>{{ patient.first_name }} {{ patient.last_name|upper }}</td>
                                    <td class="addresses">{{ patient.address }}
                                        <br> {{ patient.postcode }} {{ patient.city }}</td>
                                </tr>
                                {% empty %}
                                <!-- Fake data for design purposes-->
                                <tr>
                                    <td colspan="4">Aucun rendez-vous à afficher !</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>

                </div>
                <div id="map-container" class="col-md-6">
                    <div id="map_canvas" style="width:500px; height:400px"></div>
                    <br/>
                    <div class="table-responsive">
                        <table class="table table-stripped" id="map-legend">
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 top-spaced">
                    <p class="text-center">Les soins à faire cette semaine</p>

                    <div class="table-responsive">
                        <table class="table table-stripped">
                            <tr>
                                <th>Patient</th>
                                <th>Soin</th>
                                <th>À faire le</th>
                            </tr>
                            {% for need in needs %}
                                <tr class="clickable-row" data-href="{% url 'patient:patient_info' need.patient.id %}">
                                    <td>{{ need.patient.first_name }} {{ patient.last_name|upper }}</td>
                                    <td>{{ need.need_string }}</td>
                                    <td>{{ need.date|date:"D  d-m-Y" }}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="3">Pas de soin requis cette semaine !</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>


    </section>
{% endblock %}

{% block javascript_child %}
    <script>

        // Initializing a map from Google Maps
        var map = null;
        initialize();

        // Scrapping data from HTML to get addresses and initializing colors array for different nurses
        var appointments = [];
        var nurses = [];
        var colors_to_use = [];
        var k = 0;
        var colors = ["red", "blue", "green", "yellow", "orange", "purple", "pink", "ltblue"];
        var nurses_html = document.getElementsByClassName('nurses');
        var addresses = (document.getElementsByClassName('addresses'));

        var dates_html = document.getElementsByClassName('dates');
        var first_date = dates_html[0].innerText;

        for (var i = 0; i < addresses.length; i++) {
            if (dates_html[i].innerText == first_date) {
                appointments.push(addresses[i].innerText);
                nurses.push(nurses_html[i].innerText);
                var icon = "http://www.google.com/intl/en_us/mapfiles/ms/micons/" + colors[k] + "-dot.png";
                if (i > 0) {
                    if (nurses[i] != nurses[i - 1] && k < 8) {
                        k++;
                        icon = "http://www.google.com/intl/en_us/mapfiles/ms/micons/" + colors[k] + "-dot.png";
                        $('#map-legend').append("<tr><td><img src=" + icon + "></td><td>" + nurses[i] + "</td></tr>");
                    }
                } else {
                    $('#map-legend').append("<tr><td><img src=" + icon + "></td><td>" + nurses[0] + "</td></tr>");
                }
                colors_to_use.push(colors[k]);
            }
        }

        // Calling Google Geocode API to get coordinates and add markers on the Google map
        $.each(colors_to_use, function(index, value) {
            $.ajax({
                url: "https://maps.googleapis.com/maps/api/geocode/json?",
                type: "get",
                data: {
                    address: appointments[index],
                    key: "AIzaSyBXBuzaBwXYfU1SeuwD1vTBLPL8J0vqv3s"
                },
                success: function (response) {
                    var address = response["results"][0]["address_components"][0]["long_name"] + ", " +
                        response["results"][0]["address_components"][1]["long_name"] + " | " +
                        response["results"][0]["address_components"][2]["long_name"];
                    var lat = response["results"][0]["geometry"]["location"]["lat"];
                    var lng = response["results"][0]["geometry"]["location"]["lng"];

                    addMarker(map, address, lat, lng, value);
                },
                error: function (response) {
                    console.log("erreur" + response);
                }
            })
        });

    </script>
    <script>
        $(function () {
            $('#datetimepicker12').datetimepicker({
                viewMode: 'years',
                format: 'DD/MM/YYYY'
            });
        });
        $('#button-optimize').on('click', function () {
            var $btn = $(this).button('loading');
            var $form = $('#optimizeForm');
            $.ajax({
                url: $form.attr('action'),
                type: $form.attr('method'),
                data: $form.serialize(),
                success: function(response){
                    if (response=="Done") {
                        $('#success-optimize').text("L'optimisation a bien été effectuée !");
                        window.location.reload();
                    } else
                        $('#success-optimize').text("Vous n'avez pas de soin à effectuer aujourd'hui.");
                },
                error: function (response) {
                    $('#success-optimize').text("Désolé... une erreur est survenue.");
                }
            });
            $btn.button('reset');
        });
    </script>
    <script>
        jQuery(document).ready(function ($) {
            $(".clickable-row").hover(function () {
                $(this).css("background-color", "#f9f9f9").css("cursor", "pointer");
            });
            $(".clickable-row").click(function () {
                window.document.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

tournee_infirmiers/home/templates/home/home.html
{% extends "home_layout.html" %}
{% load staticfiles %}
{% block home_content %}
<link rel="stylesheet" href="{% static 'home/css/home_style.css' %}">
<div style="background-size: cover;"
     class="home_banner">


</div>
<div class="container-fluid">
    <div class="col-xs-6 col-xs-offset-3 home_form_div">
        <div class="title_home_form_div row">
            <h1 class="text-center">Votre tournée n'aura jamais été aussi rapide</h1>
        </div>
        <a href="{% url 'user:register' %}">
            <button class="center-block button_home"> Inscrivez-vous</button>
        </a>
    </div>
</div>

<!-- Footer -->
<footer class="footer">
    <div class="container">
        <h2>Optimisez votre tournée avec notre application web !</h2>
    </div>
</footer>
{% endblock %}

{% block javascript_child %}

{% endblock %}