tournee_infirmiers/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='root'),
    url(r'^home/', views.home, name='home'),
    url(r'^dashboard/(\d+)/(\d+)/(\d+)/(\d+)$', views.dashboard, name='dashboard_custom'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
]

tournee_infirmiers/tournee_infirmiers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('user.urls')),
	url(r'^', include('event.urls')),
	url(r'^', include('availability.urls')),
	url(r'^', include('treatment.urls')),
	url(r'^', include('optimizer.urls')),
	url(r'^', include('home.urls')),
	url(r'^', include('patient.urls')),
    url(r'^admin/', admin.site.urls),
]

tournee_infirmiers/user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import *
from user import views as user_views

app_name = 'user'
urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^register/new_nurse/$', nurse, name='new_nurse'),
    url(r'^register/save_office/$', create_office, name='create_office'),
    url(r'^register/success/$', register_success),
    url(r'^error_login/', user_views.error_login),
    url(r'^account/$', user_views.account, name='account'),
    url(r'^account/nurse/(\d+)$', user_views.nurse_info, name='nurse_info'),
    url(r'^nurse/(\d+)/edit$', user_views.edit_nurse_info, name='edit_nurse_info'),
    url(r'^office/edit/$', user_views.edit_office_info, name='edit_office_info'),
    url(r'^login/$', auth_views.login, {'template_name': 'user/login.html'}, name='login'),
    url(r'^logged_out/$', auth_views.logout, {'template_name': 'user/logged_out.html'}, name='logout'),
]

tournee_infirmiers/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}Tournee infirmier{% endblock %}</title>
		{% block stylesheets %}
			<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/base_style.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
		{% endblock %}
	</head>

	<body>

	<div id="wrapper">

		<div id="header">

		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="{% url 'home:dashboard' %}">La tournée des infirmiers</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-right">
		        {% if request.user.is_authenticated %}
		        	<li class="dropdown">
		        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bonjour {{user.username}}<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'home:dashboard' %}">Mon espace</a></li>
							<li><a href="{% url 'user:logout' %}">Déconnexion</a></li>
						</ul>
					</li>
		        {% else %}
			        <li><a href="{% url 'user:register' %}">Inscription</a></li>
			        <li><a href="{% url 'user:login' %}">Connexion</a></li>
			    {% endif %}
		        {% comment %} <li class="dropdown">
		        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Connexion <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="{% url 'user:login' %}">Formulaire de connexion</a></li>
					</ul>
		        </li> {% endcomment %}
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>

		</div>
    	<!-- Content -->

		<div class="content">
		{% block body %}
		{% endblock %}
		</div>


		{% block javascripts %}
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
			<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/fonts/glyphicons-halflings-regular.woff"></script>
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/fonts/glyphicons-halflings-regular.tff"></script>
			<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/fonts/glyphicons-halflings-regular.woff2"></script>
			<script type="text/javascript" src="../../static/js/moment.js"></script>
			<script type="text/javascript" src="../../static/js/bootstrap-datetimepicker.js"></script>
			{% block javascript_child %}
			{% endblock %}
		{% endblock %}
	</body>
</div>